services:
  postgres:
    image: postgres:17
    container_name: order-postgres
    environment:
      POSTGRES_DB: orders_db
      POSTGRES_USER: orders_user
      POSTGRES_PASSWORD: orders_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  kafka:
    image: apache/kafka:4.3.1
    container_name: order-kafka
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/tmp/kafka-logs

volumes:
  postgres_data:
  kafka_data: